### ISSUE TITLE
moment dependency?

### ISSUE THREAD

**Issue by jwasilgeo** [jpeterson/arcgis-filter#10]
@jpeterson how is this `moment` dependency possible if it isn't part of the listed `package.json` dependencies?  I see that `date-fns` is used elsewhere throughout the source code.  ~I can change this to `date-fns` while I am making other enhancements for relative date pickers.~

https://github.com/jpeterson/arcgis-filter/blob/master/src/ArcgisFilter/components/ValueInput.js#L2

**Comment by jwasilgeo** [comment]
Is it a dependency of the `calcite-react/DatePicker`, since it is supplied directly to the `DatePicker` on https://github.com/jpeterson/arcgis-filter/blob/master/src/ArcgisFilter/components/ValueInput.js#L64?

**Comment by jpeterson** [comment]
@jwasilgeo this is a good catch. I was building `arcgis-filter` and `calcite-react` simultaneously and the fact that `moment` is a dependency of `calcite-react` is why this never actually breaks anything...

We should probably rethink whether to go all in on `moment`, or to only use `date-fns` within this project. The benefit of using `moment` is that we can work directly with `moment` primitives provided by `calcite-react/DatePicker`. So maybe we replace any usage of `date-fns` with `moment` and add `moment` as a `peerDependency`?

**Comment by jwasilgeo** [comment]
On it.
